// Generated by CoffeeScript 1.12.6
var NDLog,
  slice = [].slice;

NDLog = (function() {
  var _sprintf;

  function NDLog() {}

  NDLog.prototype.echo = function() {
    var a, b;
    a = arguments[0], b = 2 <= arguments.length ? slice.call(arguments, 1) : [];
    if (process.env.NODE_ENV === "develop") {
      return console.log(_sprintf.apply(null, [a].concat(slice.call(b))));
    }
  };

  NDLog.prototype.form = function() {
    var a, b;
    a = arguments[0], b = 2 <= arguments.length ? slice.call(arguments, 1) : [];
    return _sprintf.apply(null, [a].concat(slice.call(b)));
  };

  _sprintf = function() {
    var a, b, data, data2, i, len, match, num, repstr, zero;
    a = arguments[0], b = 2 <= arguments.length ? slice.call(arguments, 1) : [];
    for (i = 0, len = b.length; i < len; i++) {
      data = b[i];
      match = a.match(/%0\d*@/);
      if ((match != null)) {
        repstr = match[0];
        num = parseInt(repstr.match(/\d+/));
        zero = "";
        while (zero.length < num) {
          zero += "0";
        }
        data2 = (zero + data).substr(-num);
        a = a.replace(repstr, data2);
      } else {
        a = a.replace('%@', data);
      }
    }
    return a;
  };

  return NDLog;

})();

module.exports = new NDLog();

//# sourceMappingURL=ndlog.js.map
